### ISSUE TITLE
php version problem

### ISSUE THREAD

**Issue by RitliRoland** [albertxhani/wise-php#3]
I'm trying to install this package with laravel, but I get this error: 
  Package transferwise/wise-php has requirements incompatible with your PHP version, PHP extensions and Composer version:
    - transferwise/wise-php v0.2 requires ext-json ^1.6 which does not match your installed version 8.1.6.

What should I do to fix this?

**Comment by albertxhani** [comment]
Hi @RitliRoland 
I have removed the requirement fro ext-json 1.6 so now the library should be installed without any problem

Feel free to contact me if you run into any other issues,
Albert
